---
kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key
              secret: yn821Y+M2L11n7ziYknVz3oHVi7n/etfx4X1cskO86Q=
      - identity: {}