---
# tasks file for kubernetes

- name: load common tasks
  include_tasks:
    file: common.yaml
  tags:
    - always

- name: load respective tasks
  include_tasks:
    file: "{{ role }}.yaml"
  tags:
    - always
