---
- name: run basic provisioning
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  module_defaults:
    apt:
      force_apt_get: yes
  pre_tasks:
    - raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
    - setup:
  roles:
    - basic